batch addresses in box resolver
capt-nemo429/ergo-graphql pull request #45
Opened 2022-09-17 08:13 UTC by SepehrGanji

2022-09-17 23:01 UTC, capt-nemo429 requested changes
Awesome work on `BoxRepository`!

2022-09-17 23:01 UTC, capt-nemo429 commented on src/graphql/resolvers/box-resolver.ts
>    @IsEmpty({ message: REDUNDANT_QUERY_MESSAGE })
Your implementation on `BoxRepository` allows the usage of `address` and `ergoTree` without conflicts, so I think we can remove this validation.

2022-09-17 23:01 UTC, capt-nemo429 commented on src/graphql/resolvers/box-resolver.ts
>    @Field(() => String, { nullable: true })
Same as `address`

2022-09-23 12:03 UTC, SepehrGanji commented on src/graphql/resolvers/box-resolver.ts
>    @IsEmpty({ message: REDUNDANT_QUERY_MESSAGE })
Removed.

2022-09-23 12:03 UTC, SepehrGanji commented on src/graphql/resolvers/box-resolver.ts
>    @Field(() => String, { nullable: true })
Removed.

2022-10-01 23:05 UTC, capt-nemo429 approved these changes

2022-10-01 23:43 UTC, merged