fix box lookup
capt-nemo429/ergo-graphql pull request #67
Opened 2022-11-19 06:34 UTC by SepehrGanji

fix #60

2022-11-21 13:07 UTC, capt-nemo429 requested changes
Great work! Left some comments on the code. 

One remark: Let's keep the code style consistent by using camelCase. :)

2022-11-21 13:07 UTC, capt-nemo429 commented on src/context/unconfirmed-transactions-repository.ts
> +      record.inputs.forEach((input) => {
Query will fail if `inputs` isn't selected. So better to have a check if isn't empty or undefined before to proceed.

2022-11-21 13:07 UTC, capt-nemo429 commented on src/context/unconfirmed-transactions-repository.ts
> +    const u_boxes = await this.dataSource
We can avoid unnecessary database query and post data processing by first checking if `u_box_ids` isn't empty.

2022-11-24 16:49 UTC, SepehrGanji commented on src/context/unconfirmed-transactions-repository.ts
> +      record.inputs.forEach((input) => {
Done, nice catch )

2022-11-24 16:49 UTC, SepehrGanji commented on src/context/unconfirmed-transactions-repository.ts
> +    const u_boxes = await this.dataSource
Refactored.

2022-12-21 11:55 UTC, capt-nemo429 approved these changes

2022-12-21 11:57 UTC, merged